services: 
  prometheus:
    image: bitnami/prometheus:3.5.0
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      network_default:
    depends_on:
      grafana:
        condition: service_healthy
    restart: always
  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.0.10:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      network_default:

networks:
  network_default: