# Configure Docker

- name: Add user to Docker group
  users:
    name: "{{ ansible_user_id }}"   # o que é {{}}? e o que seta o "ansible_user_id"
    groups: docker
    append: yes

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
