# Configure Docker

- name: Add user to Docker group
  user:
    name: "{{ ansible_user_id }}"   # puxando a informação de user_id do inventory.ini
    groups: docker
    append: yes

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
