# Run Containers Applications

- name: Create docker-compose project directory
  file:
    path: /opt/compose
    state: directory
    mode: '0755'

- name: Copy docker-compose.yaml to server
  copy:
    src: docker-compose.yaml
    dest: /opt/compose/docker-compose.yaml

- name: Copy .env to server
  copy:
    src: .env
    dest: /opt/compose/.env

- name: Start containers with docker-compose
  ansible.builtin.command: docker compose up -d
  args:
    chdir: /opt/compose